name: test-only-pr

on:
  pull_request:
    # https://docs.github.com/ja/actions/using-workflows/events-that-trigger-workflows#pull_request
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  test:
    # https://docs.github.com/ja/actions/learn-github-actions/expressions#literals
    # https://zenn.dev/nekomaho/articles/1eef80533785c9
    # PRがドラフト以外の場合だけ、以下の処理を行う
    if: ${{ github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    steps:
      - name: echo only PR
        run: echo "*** This is Opened PR!! ***"
