name: test-only-pr

on:
  pull_request:
    # https://docs.github.com/ja/actions/using-workflows/events-that-trigger-workflows#pull_request
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  test:
    # https://docs.github.com/ja/actions/learn-github-actions/expressions#literals
    # https://zenn.dev/nekomaho/articles/1eef80533785c9
    # PRが下記の条件の場合だけテストを実施
    #   - PRがドラフトではない
    #   - ブランチ名が release から始まらない
    #   - ブランチ名が test から始まらない
    #       -> https://dev.classmethod.jp/articles/how-to-get-a-ref-branch-within-a-workflow-execution-in-github-actions/
    # if条件は自動的にGitHubActions側で式として解釈されるため、${{}}を明示的に指定する必要はない
    #   -> https://docs.github.com/ja/actions/learn-github-actions/expressions#about-expressions
    #      https://github.com/orgs/community/discussions/25641
    if: |
      github.event.pull_request.draft == false
      && !startsWith(github.head_ref, 'release')
      && !startsWith(github.head_ref, 'test')
    runs-on: ubuntu-latest
    steps:
      - name: echo condition
        run: |
          echo '1' ${{ github.event.pull_request.draft == false }}
          echo '2' ${{ !startsWith(github.head_ref, 'release') }}
          echo '3' ${{ !startsWith(github.head_ref, 'test') }}
          echo '4' ${{ github.event.pull_request.draft == false && !startsWith(github.head_ref, 'release') && !startsWith(github.head_ref, 'test')}}
      - name: echo only PR
        run: echo "*** This is Opened PR!! ***"
      - name: echo github ref
        run: |
          echo '1' $GITHUB_REF
          echo '2' ${{ github.ref }}
          echo '3' ${{ github.ref_name }}
          echo '4' ${{ github.head_ref }}
          echo '5' ${{ github.base_ref }}
